name: Flask CI/CD Pipeline

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

# Define the job to run
jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the latest version of Python

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install project dependencies

    # Step 4: Run tests (assuming you have test_app.py)
    - name: Run tests
      run: |
        python -m unittest test_app.py
